// Placeholder sidebars file for API documentation (not currently used)
// This file is referenced in docusaurus.config.ts but not implemented yet

module.exports = {
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api', // This would auto-generate sidebar from /docs/api directory
    },
  ],
};